### ISSUE TITLE
Duplicate Messages in backfilled chats

### ISSUE THREAD

**Issue by Severin-S** [mautrix/instagram#73]
When backfilling chats, the first messages are duplicated. The exact number of duplications varies, I counted between 6 and 9 times the same messages. The number of messages duplicated also varies, I counted 3-6. All chats with duplicates have more than 5 messages, all chats without have less than 5 messages. This didn't occur yesterday with bride version `mautrix-instagram 0.2.3+dev.6556cbb7`.
I cleared the cache of Element Desktop (Windows) and also verified the existente of the duplicate messages in Element Android.
current bridge version: `mautrix-instagram 0.2.3+dev.6f40e012`.

I'm not sure what to search for in the logs, please tell me what information you need :)

Relevant config:
```
    max_startup_thread_sync_count: 40
    backfill:
        enable: true
        msc2716: true
        double_puppet_backfill: false
        max_conversations: -1
        min_sync_thread_delay: 5
        unread_hours_threshold: 0
        backoff:
            thread_list: 300
            message_history: 300
        incremental:
            max_pages: 10
            max_total_pages: -1
            page_delay: 5
            post_batch_delay: 20
```
