### ISSUE TITLE
error: bridge.permissions not configured

### ISSUE THREAD

**Issue by gustawdaniel** [mautrix/instagram#77]
I have 3 files:

`docker-compose.yml` with conduit server, element and mautrix-instagram

```yml
version: '3'
services:
    homeserver:
        ### If you already built the Conduit image with 'docker build' or want to use a registry image,
        ### then you are ready to go.
        image: matrixconduit/matrix-conduit:latest
        ### If you want to build a fresh image from the sources, then comment the image line and uncomment the
        ### build lines. If you want meaningful labels in your built Conduit image, you should run docker-compose like this:
        ### CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ') VERSION=$(grep -m1 -o '[0-9].[0-9].[0-9]' Cargo.toml) docker-compose up -d
        # build:
        #     context: .
        #     args:
        #         CREATED: '2021-03-16T08:18:27Z'
        #         VERSION: '0.1.0'
        #         LOCAL: 'false'
        #         GIT_REF: origin/master
        restart: unless-stopped
        ports:
            - 8448:6167
        volumes:
            - db:/var/lib/matrix-conduit/
        environment:
            CONDUIT_SERVER_NAME: your.server.name # EDIT THIS
            CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
            CONDUIT_DATABASE_BACKEND: rocksdb
            CONDUIT_PORT: 6167
            CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
            CONDUIT_ALLOW_REGISTRATION: 'true'
            CONDUIT_ALLOW_FEDERATION: 'true'
            CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
            #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
            #CONDUIT_LOG: warn,rocket=off,_=off,sled=off
            CONDUIT_ADDRESS: 0.0.0.0
            CONDUIT_CONFIG: '' # Ignore this

    ## Uncomment if you want to use your own Element-Web App.
    ## Note: You need to provide a config.json for Element and you also need a second
    ##       Domain or Subdomain for the communication between Element and Conduit
    ## Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
    element-web:
        image: vectorim/element-web:latest
        restart: unless-stopped
        ports:
            - 8009:80
        volumes:
            - ./element_config.json:/app/config.json
        depends_on:
            - homeserver

    mautrix-instagram:
        container_name: mautrix-instagram
        image: dock.mau.dev/mautrix/instagram
        restart: unless-stopped
        volumes:
            - .:/data


volumes:
    db:
```

Element_config.json

```json
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "http://localhost:8448"
        }
    }
}
```

and automatically generated `config.yaml`

I couldn't open it as user so changed his permissions using

```
sudo chown $USER config.yaml
```

content of `config.yml` is

```yml
# Homeserver details
homeserver:
    # The address that this appservice can use to connect to the homeserver.
    address: http://localhost:8448
    # The domain of the homeserver (for MXIDs, etc).
    domain: your.server.name
    # Whether or not to verify the SSL certificate of the homeserver.
    # Only applies if address starts with https://
    verify_ssl: false
    # What software is the homeserver running?
    # Standard Matrix homeservers like Synapse, Dendrite and Conduit should just use "standard" here.
    software: standard
    # Number of retries for all HTTP requests if the homeserver isn't reachable.
    http_retry_count: 4
    # The URL to push real-time bridge status to.
    # If set, the bridge will make POST requests to this URL whenever a user's Instagram MQTT connection state changes.
    # The bridge will use the appservice as_token to authorize requests.
    status_endpoint:
    # Endpoint for reporting per-message status.
    message_send_checkpoint_endpoint:
    # Whether asynchronous uploads via MSC2246 should be enabled for media.
    # Requires a media repo that supports MSC2246.
    async_media: false

# Application service host/registration related details
# Changing these values requires regeneration of the registration.
appservice:
    # The address that the homeserver can use to connect to this appservice.
    address: http://localhost:29330
    # When using https:// the TLS certificate and key files for the address.
    tls_cert: false
    tls_key: false

    # The hostname and port where this appservice should listen.
    hostname: 0.0.0.0
    port: 29330
    # The maximum body size of appservice API requests (from the homeserver) in mebibytes
    # Usually 1 is enough, but on high-traffic bridges you might need to increase this to avoid 413s
    max_body_size: 1

    # The full URI to the database. SQLite and Postgres are supported.
    # Format examples:
    #   SQLite:   sqlite:///filename.db
    #   Postgres: postgres://username:password@hostname/dbname
    database: sqlite:///filename.db
    # Additional arguments for asyncpg.create_pool() or sqlite3.connect()
    # https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.pool.create_pool
    # https://docs.python.org/3/library/sqlite3.html#sqlite3.connect
    # For sqlite, min_size is used as the connection thread pool size and max_size is ignored.
    # Additionally, SQLite supports init_commands as an array of SQL queries to run on connect (e.g. to set PRAGMAs).
    database_opts:
        min_size: 1
        max_size: 10
    id: instagram
    # Username of the appservice bot.
    bot_username: instagrambot
    # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
    # to leave display name/avatar as-is.
    bot_displayname: Instagram bridge bot
    bot_avatar: mxc://maunium.net/JxjlbZUlCPULEeHZSwleUXQv

    # Whether or not to receive ephemeral events via appservice transactions.
    # Requires MSC2409 support (i.e. Synapse 1.22+).
    # You should disable bridge -> sync_with_custom_puppets when this is enabled.
    ephemeral_events: true

    # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
    as_token: This value is generated when generating the registration
    hs_token: This value is generated when generating the registration

# Prometheus telemetry config. Requires prometheus-client to be installed.
metrics:
    enabled: false
    listen_port: 8000

# Manhole config.
manhole:
    # Whether or not opening the manhole is allowed.
    enabled: false
    # The path for the unix socket.
    path: /var/tmp/mautrix-instagram.manhole
    # The list of UIDs who can be added to the whitelist.
    # If empty, any UIDs can be specified in the open-manhole command.
    whitelist:
    - 0
instagram:
    # Seed for generating devices. This is secret because the seed is used to generate
    # device IDs, which can apparently be used to bypass two-factor authentication after
    # logging out, because Instagram is insecure.
    device_seed: 6_3g-7Ze3qzr6rESpNwlV7lKat7_x6vJGFBaUec64S9rLmVUEMioeNKyzwcoYOz5

# Bridge config
bridge:
    # Localpart template of MXIDs for Instagram users.
    # {userid} is replaced with the user ID of the Instagram user.
    username_template: instagram_{userid}
    # Displayname template for Instagram users.
    # {displayname} is replaced with the display name of the Instagram user.
    # {username} is replaced with the username of the Instagram user.
    displayname_template: '{displayname} (Instagram)'
    # Displayname template for 1:1 chat portals. Same variables as displayname_template.
    private_chat_name_template: '{displayname}'
    # Displayname template for group chat portals. Only {name} is available.
    group_chat_name_template: '{name}'

    # Maximum length of displayname
    displayname_max_length: 100

    # The maximum number of conversations that should be synced when we get a
    # message sync error. In general, 1 page (20) is sufficient.
    max_startup_thread_sync_count: 20
    # Whether or not to use /sync to get read receipts and typing notifications
    # when double puppeting is enabled
    sync_with_custom_puppets: false
    # Whether or not to update the m.direct account data event when double puppeting is enabled.
    # Note that updating the m.direct event is not atomic (except with mautrix-asmux)
    # and is therefore prone to race conditions.
    sync_direct_chat_list: false
    # Allow using double puppeting from any server with a valid client .well-known file.
    double_puppet_allow_discovery: false
    # Servers to allow double puppeting from, even if double_puppet_allow_discovery is false.
    double_puppet_server_map:
        example.com: https://example.com
    login_shared_secret_map:
        example.com: foo
    federate_rooms: true
    # Settings for backfilling messages from Instagram.
    backfill:
        # Whether to enable backfilling at all.
        #
        # This requires a server with MSC2716 support, which is currently an
        # experimental feature in synapse. It can be enabled by setting
        # experimental_features -> msc2716_enabled to true in homeserver.yaml.
        #
        # Note that prior to Synapse 1.49, there were some bugs with the
        # implementation, especially if using event persistence workers. There
        # are also still some issues in Synapse's federation implementation.
        enable: false
        # Use MSC2716 for backfilling? If this is disabled, backfilling only happens when syncing threads,
        # and the incremental settings below don't apply.
        #
        # This requires a server with MSC2716 support, which is currently an experimental feature in Synapse.
        # It can be enabled by setting experimental_features -> msc2716_enabled to true in homeserver.yaml.
        msc2716: false
        # Use double puppets for backfilling?
        # In order to use this, the double puppets must be in the appservice's user ID namespace
        # (because the bridge can't use the double puppet access token with batch sending).
        # This only affects double puppets on the local server, double puppets on other servers will never be used.
        double_puppet_backfill: false
        # The maximum number of conversations that should be synced.
        # Other conversations will be backfilled on demand when the start PM
        # provisioning endpoint is used or when a message comes in from that
        # chat.
        # If set to -1, all conversations will by synced.
        max_conversations: 20
        # The minimum amount of time to wait between syncing each thread. This
        # helps avoid situations where you sync too quickly.
        min_sync_thread_delay: 5
        # If this value is greater than 0, then if the conversation's last
        # message was more than this number of hours ago, then the conversation
        # will automatically be marked it as read.
        # Conversations that have a last message that is less than this number
        # of hours ago will have their unread status synced from Instagram.
        unread_hours_threshold: 0

        # Settings for how quickly to backoff when rate-limits are encountered
        # while backfilling.
        backoff:
            # How many seconds to wait after getting rate limited during a
            # thread list fetch.
            thread_list: 300
            # How many seconds to wait after getting rate limited during a
            # message history fetch.
            message_history: 300

        # Settings for backfills.
        #
        # During initial/incremental sync, the entirety of the thread that is
        # available will be backfilled. For example, on initial sync, about 20
        # messages are included for each thread in the thread list returned by
        # the server. After that, incremental backfills will be run for each of
        # the portals in a round-robin fashion until all portals have been
        # backfilled as configured below.
        incremental:
            # The maximum number of pages to backfill per batch.
            max_pages: 10
            # The maximum number of total pages to backfill per portal.
            # If set to -1, infinite pages will be synced.
            max_total_pages: -1
            # The number of seconds to wait between backfilling each page.
            page_delay: 5
            # The number of seconds to wait after backfilling the batch of
            # messages.
            post_batch_delay: 20

    periodic_reconnect:
        # Interval in seconds in which to automatically reconnect all users.
        # This can be used to automatically mitigate the bug where Instagram stops sending messages.
        # Set to -1 to disable periodic reconnections entirely.
        interval: -1
        # Whether or not the bridge should backfill chats when reconnecting.
        resync: true
        # Should even disconnected users be reconnected?
        always: false

    # URL to call to retrieve a proxy URL from (defaults to the http_proxy environment variable).
    get_proxy_api_url:

    # End-to-bridge encryption support options.
    #
    # See https://docs.mau.fi/bridges/general/end-to-bridge-encryption.html for more info.
    encryption:
        # Allow encryption, work in group chat rooms with e2ee enabled
        allow: false
        # Default to encryption, force-enable encryption in all portals the bridge creates
        # This will cause the bridge bot to be in private chats for the encryption to work properly.
        default: false
        # Whether to use MSC2409/MSC3202 instead of /sync long polling for receiving encryption-related data.
        appservice: false
        # Require encryption, drop any unencrypted messages.
        require: false
        # Enable key sharing? If enabled, key requests for rooms where users are in will be fulfilled.
        # You must use a client that supports requesting keys from other users to use this feature.
        allow_key_sharing: false
        # What level of device verification should be required from users?
        #
        # Valid levels:
        #   unverified - Send keys to all device in the room.
        #   cross-signed-untrusted - Require valid cross-signing, but trust all cross-signing keys.
        #   cross-signed-tofu - Require valid cross-signing, trust cross-signing keys on first use (and reject changes).
        #   cross-signed-verified - Require valid cross-signing, plus a valid user signature from the bridge bot.
        #                           Note that creating user signatures from the bridge bot is not currently possible.
        #   verified - Require manual per-device verification
        #              (currently only possible by modifying the `trust` column in the `crypto_device` database table).
        verification_levels:
            # Minimum level for which the bridge should send keys to when bridging messages from Telegram to Matrix.
            receive: unverified
            # Minimum level that the bridge should accept for incoming Matrix messages.
            send: unverified
            # Minimum level that the bridge should require for accepting key requests.
            share: cross-signed-tofu
        # Options for Megolm room key rotation. These options allow you to
        # configure the m.room.encryption event content. See:
        # https://spec.matrix.org/v1.3/client-server-api/#mroomencryption for
        # more information about that event.
        rotation:
            # Enable custom Megolm room key rotation settings. Note that these
            # settings will only apply to rooms created after this option is
            # set.
            enable_custom: false
            # The maximum number of milliseconds a session should be used
            # before changing it. The Matrix spec recommends 604800000 (a week)
            # as the default.
            milliseconds: 604800000
            # The maximum number of messages that should be sent with a given a
            # session before changing it. The Matrix spec recommends 100 as the
            # default.
            messages: 100

    # Whether or not to explicitly set the avatar and room name for private
    # chat portal rooms. This will be implicitly enabled if encryption.default is true.
    private_chat_portal_meta: false
    # Whether or not the bridge should send a read receipt from the bridge bot when a message has
    # been sent to Instagram.
    delivery_receipts: false
    # Whether or not delivery errors should be reported as messages in the Matrix room.
    delivery_error_reports: false
    # Whether the bridge should send the message status as a custom com.beeper.message_send_status event.
    message_status_events: false
    # Set this to true to tell the bridge to re-send m.bridge events to all rooms on the next run.
    # This field will automatically be changed back to false after it,
    # except if the config file is not writable.
    resend_bridge_info: false
    # Whether or not unimportant bridge notices should be sent to the user.
    # (e.g. connected, disconnected but will retry)
    unimportant_bridge_notices: true
    # Disable bridge notices entirely
    disable_bridge_notices: false
    # Send captions in the same message as images. This will send data compatible with both MSC2530 and MSC3552.
    # This is currently not supported in most clients.
    caption_in_message: false

    # Should Matrix m.notice-type messages be bridged?
    bridge_notices: true

    # Provisioning API part of the web server for automated portal creation and fetching information.
    # Used by things like mautrix-manager (https://github.com/tulir/mautrix-manager).
    provisioning:
        # Whether or not the provisioning API should be enabled.
        enabled: true
        # The prefix to use in the provisioning API endpoints.
        prefix: /_matrix/provision/v1
        # The shared secret to authorize users of the API.
        # Set to "generate" to generate and save a new token.
        shared_secret: SIVYauktlF9EP7B6vFqKDAD6p6KpYwsmJ3J3ddWAFIbuYd2PVYsyYvUk97-xZflA
        # Segment API key to enable analytics tracking for web server endpoints. Set to null to disable.
        segment_key:

    # The prefix for commands. Only required in non-management rooms.
    command_prefix: '!ig'

    # Permissions for using the bridge.
    # Permitted values:
    #      relay - Allowed to be relayed through the bridge, no access to commands.
    #       user - Use the bridge with puppeting.
    #      admin - Use and administrate the bridge.
    # Permitted keys:
    #        * - All Matrix users
    #   domain - All users on that homeserver
    #     mxid - Specific user
    permissions:
        "*": admin
#        "*": relay
#        "your.server.name": user
#        "@gustawdaniel:your.server.name": admin
    relay:
        # Whether relay mode should be allowed. If allowed, `!ig set-relay` can be used to turn any
        # authenticated user into a relaybot for that chat.
        enabled: false
        # The formats to use when sending messages to Instagram via a relay user.
        #
        # Available variables:
        #   $sender_displayname - The display name of the sender (e.g. Example User)
        #   $sender_username    - The username (Matrix ID localpart) of the sender (e.g. exampleuser)
        #   $sender_mxid        - The Matrix ID of the sender (e.g. @exampleuser:example.com)
        #   $message            - The message content
        #
        # Note that Instagram doesn't support captions for images, so images won't include any indication of being relayed.
        message_formats:
            m.text: '$sender_displayname: $message'
            m.notice: '$sender_displayname: $message'
            m.emote: '* $sender_displayname $message'

# Python logging configuration.
#
# See section 16.7.2 of the Python documentation for more info:
# https://docs.python.org/3.6/library/logging.config.html#configuration-dictionary-schema
logging:
    version: 1
    formatters:
        colored:
            (): mautrix_instagram.util.ColorFormatter
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
        normal:
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: colored
    loggers:
        mau:
            level: DEBUG
        mauigpapi:
            level: DEBUG
        aiohttp:
            level: INFO
        paho.mqtt:
            level: INFO
    root:
        level: DEBUG
        handlers: [console]
```

After `docker-compose up` I see:

```
mautrix-instagram    | [2022-12-27 22:40:33,721] [CRITICAL@mau.init] Configuration error: bridge.permissions not configured
mautrix-instagram exited with code 11
```
